
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_TCP_PORT: '3307'
    ports:
      - "3307:3307" 
    expose:
      # Opens port 3306 on the container
      - '3307'
    volumes:
      - ./mysql:/var/lib/mysql